language: node_js
node_js:
  - 13
services:
  - docker
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed truongle1111/udagram-api-feed:v1
  - docker tag udagram-api-user truongle1111/udagram-api-user:v1
  - docker tag udagram-frontend truongle1111/udagram-frontend:v1
  - docker tag reverseproxy truongle1111/reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push truongle1111/udagram-api-feed:tagname
  - docker push truongle1111/udagram-api-user:tagname
  - docker push truongle1111/udagram-frontend:tagname
  - docker push truongle1111/udagram-reverseproxy:tagname